apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: argo-sso-cluster-reader-writer
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workfloweventbindings
  - workfloweventbindings/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  - clusterworkflowtemplates
  - clusterworkflowtemplates/finalizers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: argo-sso-cluster-reader-writer
  namespace: {{ include "argo-workflows.namespace" . | quote }}
  annotations:
    kubernetes.io/service-account.name: "argo-sso-cluster-reader-writer"
    kubernetes.io/service-account.namespace: {{ include "argo-workflows.namespace" . | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-sso-cluster-reader-writer
  namespace: {{ include "argo-workflows.namespace" . | quote }}
  annotations:
    workflows.argoproj.io/rbac-rule:  "'{{ .Values.clusterSsoUsers.ssoReaderWriterGroup}}' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
secrets:
   - name: argo-sso-cluster-reader-writer

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-sso-cluster-reader-writer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-sso-cluster-reader-writer
subjects:
  - kind: ServiceAccount
    name: argo-sso-cluster-reader-writer
    namespace: {{ include "argo-workflows.namespace" . | quote }}
