apiVersion: v2
appVersion: v3.5.6
name: argo-workflows
description: A Helm chart for Argo Workflows
type: application
version: 0.41.4
icon: https://argo-workflows.readthedocs.io/en/stable/assets/logo.png

