{{- range .Values.namespaceSsoUsers }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: argo-sso-reader
  namespace: {{ .namespaceName }}
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workfloweventbindings
  - workfloweventbindings/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  - clusterworkflowtemplates
  - clusterworkflowtemplates/finalizers
  verbs:
  - get
  - list
  - watch
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: argo-sso-reader
  namespace: {{ .namespaceName }} 
  annotations:
    kubernetes.io/service-account.name: "argo-sso-reader"
    kubernetes.io/service-account.namespace: "{{ .namespaceName }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-sso-reader
  namespace: {{ .namespaceName }}
  annotations:
    workflows.argoproj.io/rbac-rule:  "'{{ .ssoReaderGroup}}' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "1"
secrets:
   - name: argo-sso-reader

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-sso-reader-binding
  namespace: {{ .namespaceName }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name:  argo-sso-reader
subjects:
- kind: ServiceAccount
  name: argo-sso-reader
  namespace: {{ .namespaceName }}

{{- end }}